### ISSUE TITLE
Loop Detection Question

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa#191]
I had a question on the feature `characteristic: loop`.

I have a function that does contain a loop but the characteristic appears to not be recognized.

In sample `1d8fd13c890060464019c0f07b928b1a` (Located in the `capa-testfiles` repo) at offset: `0x401920`. 

The function graph contains the following blocks:
![image](https://user-images.githubusercontent.com/57954766/88332303-4d5d3380-ccfc-11ea-922b-d0208344daf5.png)

I wrote a dummy rule to see if I could trigger on the behaviour of a loop
```
rule:
  meta:
    name: loop
    namespace: loop
    scope: function
  features:
    - and:
      - characteristic: loop
```
The only result that I'm getting back is @ `0x402360` and not `0x401920`
```
loop
namespace  loop
scope      function
function @ 0x402360
  and:
    characteristic: loop @ 0x402360
```

Any help or guidance would be appreciated.
