### ISSUE TITLE
Enable descriptions for statement nodes

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#194]
### Summary

Enable descriptions for statement nodes such as `and` and `or`.

For example:
```
- or:
  - string: Environment
  - string: windir
  - match: set registry value
description: Modify %windir% environment variable

```

### Motivation

@re-fox has provided a use of case in: fireeye/capa-rules/pull/51 

### Additional context

We need to come up with a way to render this in the `-vv` output. Suggestions:

##### 1 - Inline as a comment
```
- or: # Modify %windir% environment variable
  - string: Environment @ 0x401213
  - string: windir @ 0x40121A
```

##### 2 - Inline with the already existent description symbol
```
- or: = Modify %windir% environment variable
  - string: Environment @ 0x401213
  - string: windir @ 0x40121A
```

##### 3 - Not in line
```
- or:
  - string: Environment @ 0x401213
  - string: windir @ 0x40121A
description: Modify %windir% environment variable
```

I like option 2. What do you think? Any other ideas?

This also need to be added in capa explorer.
