### ISSUE TITLE
extend offset feature to account for architecture/bitness

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#210]
on different architectures (specifically x32 vs x64) the sizes and layouts of structures will differ. right now, capa doesn't have an easy way to limit its offset features based on the architecture, which means there's a greater chance of FP binaries of the wrong bitness. we should consider extending the offset features with tags specifying what bitnesses they match.

initially motivated here: https://github.com/fireeye/capa-rules/pull/54#discussion_r461701514

best sketch so far:

```yml
- or:
  - offset/x32: 0x24 = pe.szExeFile
  - offset/x64: 0x?? = pe.szExeFile
```

this would be an easy add, since we could just emit an additional feature for each offset that's tagged with the bitness.
