### ISSUE TITLE
Should we support inline descriptions for statements?

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa#214]
### Summary
Since https://github.com/fireeye/capa/pull/209, we support the two-lines syntax for descriptions. Should we support inline syntax as we do with features (expect strings) as well?

### Motivation

The rule [`load-code/pe/parse-pe-header.yml`](https://github.com/fireeye/capa-rules/blob/master/load-code/pe/parse-pe-header.yml) includes:
```
- or:
  - and:  # 32-bit
    - offset: 0x50 = IMAGE_NT_HEADERS.OptionalHeader.SizeOfImage
    - offset: 0x34 = IMAGE_NT_HEADERS.OptionalHeader.ImageBase
  - and:  # 64-bit
    - offset: 0x50 = IMAGE_NT_HEADERS64.OptionalHeader.SizeOfImage
    - offset: 0x30 = IMAGE_NT_HEADERS64.OptionalHeader.ImageBase
```

which could naturally be changed to inline descriptions:
```
- or:
  - and: = 32-bit
    - offset: 0x50 = IMAGE_NT_HEADERS.OptionalHeader.SizeOfImage
    - offset: 0x34 = IMAGE_NT_HEADERS.OptionalHeader.ImageBase
  - and: = 64-bit
    - offset: 0x50 = IMAGE_NT_HEADERS64.OptionalHeader.SizeOfImage
    - offset: 0x30 = IMAGE_NT_HEADERS64.OptionalHeader.ImageBase
```

The current supported syntax doesn't look as good here:
```
- or:
  - and:
    - offset: 0x50 = IMAGE_NT_HEADERS.OptionalHeader.SizeOfImage
    - offset: 0x34 = IMAGE_NT_HEADERS.OptionalHeader.ImageBase
    description: 64-bits
  - and:
    - offset: 0x50 = IMAGE_NT_HEADERS64.OptionalHeader.SizeOfImage
    - offset: 0x30 = IMAGE_NT_HEADERS64.OptionalHeader.ImageBase
    description: 64-bits
```

Also, when using the `-vv` option, the inline syntax is displayed.
