### ISSUE TITLE
Python exception when trying to create a rule that involves counting strings

### ISSUE THREAD

**Issue by D4nch3n** [fireeye/capa#241]
### Description

When attempting to count the number of occurrences of a string in the file context, capa crashes with an exception when trying to create a new Feature() object.

### Steps to Reproduce

1. Create a capa rule with the following:
```
rule:
  meta:
    name: test
    namespace: test
    scope: file
  features:
    - count(string("This program cannot be run in DOS mode")): 1
```

2. Run this rule against any PE fle using the -r option

**Expected behavior:**

Either display whether the file matched the given count rule, or display a message saying that count isn't supported in the file scope.

**Actual behavior:**

Capa crashes with the following exception:

![image](https://user-images.githubusercontent.com/26351077/90523176-6dc4b600-e121-11ea-9f61-ad96247b6f3a.png)

### Versions

capa 1.1.0 for linux (running on ubuntu 18.04)

### Additional Information

None

**Comment by Ana06** [comment]
This also fails with `function` scope:

```
rule:
  meta:
    name: test
    namespace: test
    scope: function
  features:
    - count(string("This program cannot be run in DOS mode")): 1
```

And it fails in current master as well.

So, it looks like a bug. Thanks for reporting @D4nch3n! 👍
