### ISSUE TITLE
missing offset feature from vivisect backend

### ISSUE THREAD

**Issue by edeca** [fireeye/capa#276]
### Description

I am trying to write a rule to detect QuickLZ decompression. I get different results when trying to detect in shellcode using both IDA and the commandline tool.

I'm not sure whether my rule is broken or the various backends handle shellcode differently.

### Steps to Reproduce

1. Load the reproductions below in IDA.
2. Run capa explorer from plugin with the rule.
3. No matches found, except in one IDB (!?).

I *do* get matches in one of my IDBs (unfortunately this cannot be shared). I noticed the inconsistency when loading the rules in another IDA instance, where I did not get any matches. In both databases the functions are created (they appear in the function list). This is what caused me to report as a potential bug.

At command line:

1. Save reproduction to file using hex editor.
2. Run `capa.exe --format sc32 -r c:\path\to\rules quicklz_internal_32.bin`.
3. No capabilities found.

**Expected behavior:**

Consistent matches (or lack of matches!).

**Actual behavior:**

Works in one IDA database, does not work in others.

### Versions

* capa 1.2.0
* Python 2.7.18 (32 bit) on Windows 10 (64 bit) for tests at command line
* IDA 7.5 with Python 3.7.5

```
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] 
IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
```

### Additional Information

32-bit repro: `568B318BC6C1E80C33C625FF0F0000890C82C6841000400000015EC3`
64-bit repro: `8B02C1E80C330225FF0F0000488914C1C684080080000001C3`

Attempted rule:

```
rule:
  meta:
    name: decompress data using QuickLZ
    namespace: data-manipulation/compression
    author: david@edeca.net
    description: detects the inner decompression loop from QuickLZ
    scope: function
    references:
      - http://www.quicklz.com/
  features:
    - and:
      - mnemonic: xor
      - mnemonic: shr
      - mnemonic: and
      - number: 0xC
      - number: 0xFFF
      - or:
        - offset: 0x4000
        - offset: 0x8000
```

Output from command line tool:

```
C:\Python27\Scripts\capa.exe --format sc32 -r 'C:\Users\<vm>\Desktop\Rules\capa' '.\quicklz_internal_32.bin'
loading : 100%|##################################################################| 2/2 [00:00<00:00, 40.00     rules/s]
matching: 100%|##################################################################| 1/1 [00:00<00:00, 62.50 functions/s]
+------------------------+------------------------------------------------------------------------------------+
| md5                    | c21e618f768fb8e4a9a6b68cd7aed271                                                   |
| sha1                   | 74674c0501443eb37f928d35a673a74a3d50ba80                                           |
| sha256                 | b3211fbe39072bb29e094b46da4b95cc0034eae91af01fd85719a9ac1abaa6e2                   |
| path                   | quicklz_internal_32.bin                                                            |
+------------------------+------------------------------------------------------------------------------------+

no capabilities found
```
