### ISSUE TITLE
feature: function count

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa#543]
```yaml
rule:
  meta:
    name: contain few functions
    examples:
      - 068a76d4823419b376d418cf03215d5c
  features:
    - count(function): 10 or less
```

Is something like this possible or would we need a new feature?

Would it be worth adding? Currently I can only think of using this for packer detection.

**Comment by williballenthin** [comment]
> Is something like this possible or would we need a new feature?

I don't think we can do this today. Function features bubble up to File features, so the `scope: file` would be appropriate; however, we don't extract a feature for each function start (how else would this be used?) so there's nothing relevant to work with at the file scope.

**Comment by williballenthin** [comment]
we could approximate this today like so:

```yml
scope: file
features:
  - count(characteristic(calls to)): 10 or less
```
which says: "there are ten or fewer resolved calls"

(note: i haven't tested this rule, but i *think* it should work)
